textmate.el:
  repo: git@github.com:pat-maddox/textmate.el.git
  path: vendor
yasnippet.el:
  repo: git@github.com:pat-maddox/yasnippet.el.git
  path: vendor
rspec-mode.el:
  repo: git@github.com:pat-maddox/rspec-mode.el.git
  path: vendor
magit:
  repo: git://gitorious.org/magit/mainline.git
  path: vendor
gist:
  repo: git://github.com/defunkt/gist.el.git
  path: vendor
cheat.el:
  repo: git://github.com/defunkt/cheat.el.git
  path: vendor
ecb:
  repo: git://github.com/pat-maddox/ecb.git
  path: vendor
