textmate.el:
  repo: git@github.com:pat-maddox/textmate.el.git
  path: vendor
yasnippet.el:
  repo: git@github.com:pat-maddox/yasnippet.el.git
  path: vendor
rspec-mode.el:
  repo: git@github.com:pat-maddox/rspec-mode.el.git
  path: vendor
magit:
  repo: git://github.com/technomancy/magit.git
  path: vendor
